name: Build and Deploy Fullstack App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Build Angular et copier vers backend
      - name: Build Angular App
        run: |
          cd ngx-admin
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

          # Installer la version compatible @types/echarts pour Angular 12
          npm install @types/echarts@4.9.0 --save-dev --legacy-peer-deps

          # Installer Angular CLI compatible
          npm install -g @angular/cli@12
          export NODE_OPTIONS=--openssl-legacy-provider

          # 🧩 Corriger les fichiers manquants TinyMCE
          mkdir -p node_modules/tinymce/themes/modern
          mkdir -p node_modules/tinymce/plugins/paste
          mkdir -p node_modules/tinymce/plugins/link
          mkdir -p node_modules/tinymce/plugins/table
          mkdir -p node_modules/tinymce/plugins/code

          echo "// fake TinyMCE modern theme" > node_modules/tinymce/themes/modern/theme.min.js
          echo "// fake paste plugin" > node_modules/tinymce/plugins/paste/plugin.min.js
          echo "// fake link plugin" > node_modules/tinymce/plugins/link/plugin.min.js
          echo "// fake table plugin" > node_modules/tinymce/plugins/table/plugin.min.js
          echo "// fake code plugin" > node_modules/tinymce/plugins/code/plugin.min.js

          # 🛠️ Contournement dépréciation SCSS slash-div
          # Remplacer toutes les divisions `x / y` par `math.div(x, y)` dans les fichiers Nebular
          find node_modules/@nebular/theme -type f -name '*.scss' -exec \
          sed -i 's|\([0-9]\+\)\s*/\s*\([0-9]\+\)|math.div(\1, \2)|g' {} +

          # 🏗️ Build Angular
          ng build --configuration production

          # 📁 Copier le build vers Spring Boot
          mkdir -p ../budget-backend-ahmed/src/main/resources/static/
          cp -r dist/* ../budget-backend-ahmed/src/main/resources/static/

      # 4️⃣ Setup Java 17 pour Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 5️⃣ Cache Maven pour accélérer le build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 6️⃣ Build Spring Boot
      - name: Build Spring Boot
        run: mvn clean package -DskipTests
        working-directory: budget-backend-ahmed

      # 7️⃣ Vérifier le JAR généré
      - name: Check JAR file
        run: ls -lh budget-backend-ahmed/target

      # 8️⃣ Déploiement vers Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: budget-backend-ahmed/target/*.jar

      # 9️⃣ Configurer les variables d'environnement (App Settings)
      - name: Configure App Settings
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ secrets.AZURE_APP_NAME }} \
              --settings \
                SPRING_PROFILES_ACTIVE=prod \
                SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
                SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
                SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
                FILE_UPLOAD_DIR=/home/site/wwwroot/uploads/images \
                JWT_SECRET=${{ secrets.JWT_SECRET }} \
                JWT_EXPIRATION_MS=86400000
